package com.yaka.tp1.models;
// Generated 26 mai 2014 21:15:50 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private int id;
     private String firstname;
     private String lastname;
     private Date created;

    public Users() {
    }

    public Users(int id, String firstname, String lastname, Date created) {
       this.id = id;
       this.firstname = firstname;
       this.lastname = lastname;
       this.created = created;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }




}


